[ 2024-12-25 18:42:18,080 ] werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.233:5000
[ 2024-12-25 18:42:18,081 ] werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2024-12-25 18:42:41,738 ] werkzeug - INFO - 127.0.0.1 - - [25/Dec/2024 18:42:41] "GET / HTTP/1.1" 200 -
[ 2024-12-25 18:42:42,271 ] werkzeug - INFO - 127.0.0.1 - - [25/Dec/2024 18:42:42] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2024-12-25 18:42:57,947 ] werkzeug - INFO - 127.0.0.1 - - [25/Dec/2024 18:42:57] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[ 2024-12-25 18:42:57,954 ] werkzeug - ERROR - Error on request:
Traceback (most recent call last):
  File "/home/dpach/.conda/envs/gun_detection/lib/python3.11/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/home/dpach/.conda/envs/gun_detection/lib/python3.11/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/home/dpach/.conda/envs/gun_detection/lib/python3.11/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/home/dpach/.conda/envs/gun_detection/lib/python3.11/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'FileNotFoundError' object is not iterable
